/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labirintus;


import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ÜtőImre(SZOFT_2023_2
 */
public class LabirintusGUI extends javax.swing.JFrame {


    
    //Konstruktor
    String felhasznaloNev;
    int oldalszam = 1;
    public LabirintusGUI()  {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        
        String[] oldalTarolo = new String[5];
        oldalTarolo[0] = "Kardod könnyedén áthatol a spóragolyó vékonykülső burkán. Sűrű barna spórafelhő csap ki a golyóból, és körülvesz. Némelyik spóra a bőrödhöz tapad, és rettenetes viszketést okoz. Nagy daganatok nőnek az arcodon és karodon, és a bőröd mintha égne. 2 ÉLETERŐ pontot veszítesz. Vadul vakarózva átléped a leeresztett golyót, és keletnek veszed az utad.";
        oldalTarolo[0] = "A doboz teteje könnyedén nyílik. Benne két aranypénzt találsz, és egy üzenetet, amely egy kis pergamenen neked szól. Előbb zsebre vágod az aranyakat, aztán elolvasod az üzenetet: - „Jól tetted. Legalább volt annyi eszed, hogy megállj és elfogadd az ajándékot. Most azt tanácsolom neked, hogy keress és használj különféle tárgyakat, ha sikerrel akarsz áthaladni Halállabirintusomon.” Azaláírás Szukumvit. Megjegyzed a tanácsot, apródarabokra téped a pergament, és tovább mészészak felé. Lapozz a 66-ra.";
        oldalTarolo[0] = "A három pár nedves lábnyomot követve az alagútnyugati elágazásában hamarosan egy újabb el-ágazáshoz érsz. Ha továbbmész nyugat felé a lábnyomokat követve, lapozz a 137-re. Ha inkább észak felé mész a harmadik pár lábnyom után, lapozz a 387-re.";
        oldalTarolo[0] = "Fölmászol a lágy sziklára, attól tartasz, hogy bár-melyik pillanatban elnyelhet. Nehéz átvergődni rajta, mert puha anyagában alig tudod a lábadat emelni, de végül átvergődsz rajta. Megkönnyebbülten érsz újra szilárd talajra, és fordulsz kelet felé.";
        oldalTarolo[0] = "Hallod, hogy elölről súlyos lépések közelednek. Egy széles, állatbőrökbe öltözött, kőbaltás, primitívlény lép elő. Ahogy meglát, morog, a földre köp, majd a kőbaltát felemelve közeledik, és mindennek kinéz, csak barátságosnak nem. Előhúzod kardodat, és felkészülsz, hogy megküzdj a Barlangi Emberrel.\nBarlangi Ember ÜGYESSÉG 7 ÉLETERŐ 7";
        
        System.out.println(oldalTarolo[3]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpOldalak = new javax.swing.JTabbedPane();
        pnlMenu = new javax.swing.JPanel();
        btnToStart = new javax.swing.JButton();
        scpJatekInfo = new javax.swing.JScrollPane();
        txaOldalnfo1 = new javax.swing.JTextArea();
        txfFelhasznaloNev = new javax.swing.JTextField();
        lblSzovegFelhasznalonev = new javax.swing.JLabel();
        pnlGame = new javax.swing.JPanel();
        scpOldalInfo = new javax.swing.JScrollPane();
        txaOldalnfo = new javax.swing.JTextArea();
        pnlGameHud = new javax.swing.JPanel();
        btnToInventory = new javax.swing.JButton();
        pnlPlayerInfo = new javax.swing.JPanel();
        lblKepSziv = new javax.swing.JLabel();
        lblKepCoin = new javax.swing.JLabel();
        lblKepAtk = new javax.swing.JLabel();
        lblKepDef = new javax.swing.JLabel();
        lblHp = new javax.swing.JLabel();
        lblPenz = new javax.swing.JLabel();
        lblAtk = new javax.swing.JLabel();
        lblDef = new javax.swing.JLabel();
        lblFelhNev = new javax.swing.JLabel();
        pnlOldalSzam = new javax.swing.JPanel();
        lblTxtOldalSz = new javax.swing.JLabel();
        lblOldalSzam = new javax.swing.JLabel();
        btnOldal1 = new javax.swing.JButton();
        btnOldal2 = new javax.swing.JButton();
        pnlInventory = new javax.swing.JPanel();
        pnlPlayerInfo1 = new javax.swing.JPanel();
        lblKepSziv1 = new javax.swing.JLabel();
        lblKepCoin1 = new javax.swing.JLabel();
        lblKepAtk1 = new javax.swing.JLabel();
        lblKepDef1 = new javax.swing.JLabel();
        lblHp1 = new javax.swing.JLabel();
        lblPenz1 = new javax.swing.JLabel();
        lblAtk1 = new javax.swing.JLabel();
        lblDef1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halál labirintus");
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));

        tpOldalak.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tpOldalak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        pnlMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnlMenu.setPreferredSize(new java.awt.Dimension(800, 616));

        btnToStart.setBackground(new java.awt.Color(0, 0, 0));
        btnToStart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnToStart.setForeground(new java.awt.Color(255, 0, 0));
        btnToStart.setText("Kezdés");
        btnToStart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        btnToStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToStartActionPerformed(evt);
            }
        });

        scpJatekInfo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpJatekInfo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaOldalnfo1.setEditable(false);
        txaOldalnfo1.setBackground(new java.awt.Color(0, 0, 0));
        txaOldalnfo1.setColumns(20);
        txaOldalnfo1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        txaOldalnfo1.setForeground(new java.awt.Color(255, 5, 0));
        txaOldalnfo1.setLineWrap(true);
        txaOldalnfo1.setRows(5);
        txaOldalnfo1.setText("Egy versenyre nevezel, aminek a lényege, hogy át kell kelni a halállabirintuson. A labirintusban tárgyakat találhatsz és szörnyekkel kell harcoljál.");
        txaOldalnfo1.setToolTipText("");
        txaOldalnfo1.setWrapStyleWord(true);
        scpJatekInfo.setViewportView(txaOldalnfo1);

        txfFelhasznaloNev.setBackground(new java.awt.Color(0, 0, 0));
        txfFelhasznaloNev.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txfFelhasznaloNev.setForeground(new java.awt.Color(255, 255, 255));

        lblSzovegFelhasznalonev.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblSzovegFelhasznalonev.setForeground(new java.awt.Color(255, 0, 0));
        lblSzovegFelhasznalonev.setText("Felhasználónév");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(lblSzovegFelhasznalonev)
                        .addGap(324, 324, 324))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(txfFelhasznaloNev, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnToStart, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(scpJatekInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpJatekInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lblSzovegFelhasznalonev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfFelhasznaloNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnToStart, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        tpOldalak.addTab("Menu", pnlMenu);

        pnlGame.setBackground(new java.awt.Color(51, 51, 51));

        scpOldalInfo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpOldalInfo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaOldalnfo.setEditable(false);
        txaOldalnfo.setBackground(new java.awt.Color(0, 0, 0));
        txaOldalnfo.setColumns(20);
        txaOldalnfo.setFont(new java.awt.Font("Tahoma", 1, 23)); // NOI18N
        txaOldalnfo.setForeground(new java.awt.Color(255, 5, 0));
        txaOldalnfo.setLineWrap(true);
        txaOldalnfo.setRows(5);
        txaOldalnfo.setText("Miután öt percet haladtál lassan az alagútban, egy kőasztalhoz érsz, amely a bal oldali fal mellett áll. Hat doboz van rajta, egyikükre a te neved festették. Ha ki akarod nyitni a dobozt, lapozz a 270-re. Ha inkább tovább haladsz észak felé, lapozz a 66-ra.");
        txaOldalnfo.setWrapStyleWord(true);
        scpOldalInfo.setViewportView(txaOldalnfo);

        pnlGameHud.setBackground(new java.awt.Color(153, 153, 153));

        btnToInventory.setBackground(new java.awt.Color(102, 102, 102));
        btnToInventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnToInventory.setForeground(new java.awt.Color(255, 0, 0));
        btnToInventory.setText("Inventory");
        btnToInventory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToInventoryActionPerformed(evt);
            }
        });

        pnlPlayerInfo.setBackground(new java.awt.Color(204, 204, 204));
        pnlPlayerInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblKepSziv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/sziv.png"))); // NOI18N

        lblKepCoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/coin.png"))); // NOI18N

        lblKepAtk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/boko.png"))); // NOI18N

        lblKepDef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/shield.png"))); // NOI18N

        lblHp.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblHp.setText("100");

        lblPenz.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblPenz.setText("0");

        lblAtk.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblAtk.setText("5");

        lblDef.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblDef.setText("0");

        lblFelhNev.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblFelhNev.setText("Nev");

        javax.swing.GroupLayout pnlPlayerInfoLayout = new javax.swing.GroupLayout(pnlPlayerInfo);
        pnlPlayerInfo.setLayout(pnlPlayerInfoLayout);
        pnlPlayerInfoLayout.setHorizontalGroup(
            pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFelhNev))
                    .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                        .addComponent(lblKepSziv)
                        .addGap(18, 18, 18)
                        .addComponent(lblHp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                        .addComponent(lblKepCoin)
                        .addGap(18, 18, 18)
                        .addComponent(lblPenz, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                        .addComponent(lblKepAtk)
                        .addGap(18, 18, 18)
                        .addComponent(lblAtk, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                        .addComponent(lblKepDef)
                        .addGap(18, 18, 18)
                        .addComponent(lblDef, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlPlayerInfoLayout.setVerticalGroup(
            pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKepSziv)
                    .addComponent(lblHp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKepCoin)
                    .addComponent(lblPenz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKepAtk)
                    .addComponent(lblAtk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKepDef)
                    .addComponent(lblDef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFelhNev)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlOldalSzam.setBackground(new java.awt.Color(153, 153, 153));
        pnlOldalSzam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblTxtOldalSz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTxtOldalSz.setText("Oldalszám");

        lblOldalSzam.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        lblOldalSzam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOldalSzam.setText("1");

        javax.swing.GroupLayout pnlOldalSzamLayout = new javax.swing.GroupLayout(pnlOldalSzam);
        pnlOldalSzam.setLayout(pnlOldalSzamLayout);
        pnlOldalSzamLayout.setHorizontalGroup(
            pnlOldalSzamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOldalSzamLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pnlOldalSzamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOldalSzamLayout.createSequentialGroup()
                        .addComponent(lblTxtOldalSz, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOldalSzamLayout.createSequentialGroup()
                        .addComponent(lblOldalSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        pnlOldalSzamLayout.setVerticalGroup(
            pnlOldalSzamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOldalSzamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTxtOldalSz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOldalSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        btnOldal1.setBackground(new java.awt.Color(0, 0, 0));
        btnOldal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOldal1.setForeground(new java.awt.Color(255, 0, 0));
        btnOldal1.setText("270");
        btnOldal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnOldal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldal1ActionPerformed(evt);
            }
        });

        btnOldal2.setBackground(new java.awt.Color(0, 0, 0));
        btnOldal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOldal2.setForeground(new java.awt.Color(255, 0, 0));
        btnOldal2.setText("66");
        btnOldal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnOldal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldal2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGameHudLayout = new javax.swing.GroupLayout(pnlGameHud);
        pnlGameHud.setLayout(pnlGameHudLayout);
        pnlGameHudLayout.setHorizontalGroup(
            pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameHudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGameHudLayout.createSequentialGroup()
                        .addComponent(pnlPlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(pnlOldalSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameHudLayout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addGroup(pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameHudLayout.createSequentialGroup()
                                .addComponent(btnOldal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(btnOldal2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(203, 203, 203))
                            .addComponent(btnToInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        pnlGameHudLayout.setVerticalGroup(
            pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameHudLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOldalSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGameHudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOldal1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOldal2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addComponent(btnToInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlGameLayout = new javax.swing.GroupLayout(pnlGame);
        pnlGame.setLayout(pnlGameLayout);
        pnlGameLayout.setHorizontalGroup(
            pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scpOldalInfo)
                    .addComponent(pnlGameHud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnlGameLayout.setVerticalGroup(
            pnlGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGameLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(scpOldalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGameHud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        tpOldalak.addTab("Game", pnlGame);

        pnlInventory.setBackground(new java.awt.Color(51, 51, 51));

        pnlPlayerInfo1.setBackground(new java.awt.Color(204, 204, 204));
        pnlPlayerInfo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblKepSziv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/sziv.png"))); // NOI18N

        lblKepCoin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/coin.png"))); // NOI18N

        lblKepAtk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/boko.png"))); // NOI18N

        lblKepDef1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/shield.png"))); // NOI18N

        lblHp1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblHp1.setText("100");

        lblPenz1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblPenz1.setText("0");

        lblAtk1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblAtk1.setText("5");

        lblDef1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        lblDef1.setText("0");

        javax.swing.GroupLayout pnlPlayerInfo1Layout = new javax.swing.GroupLayout(pnlPlayerInfo1);
        pnlPlayerInfo1.setLayout(pnlPlayerInfo1Layout);
        pnlPlayerInfo1Layout.setHorizontalGroup(
            pnlPlayerInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKepSziv1)
                .addGap(18, 18, 18)
                .addComponent(lblHp1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKepCoin1)
                .addGap(18, 18, 18)
                .addComponent(lblPenz1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblKepAtk1)
                .addGap(18, 18, 18)
                .addComponent(lblAtk1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKepDef1)
                .addGap(18, 18, 18)
                .addComponent(lblDef1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        pnlPlayerInfo1Layout.setVerticalGroup(
            pnlPlayerInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayerInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayerInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDef1)
                    .addComponent(lblKepSziv1)
                    .addComponent(lblHp1)
                    .addComponent(lblPenz1)
                    .addComponent(lblKepCoin1)
                    .addComponent(lblKepAtk1)
                    .addComponent(lblAtk1)
                    .addComponent(lblKepDef1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPlayerInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPlayerInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );

        tpOldalak.addTab("Inventory", pnlInventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpOldalak)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpOldalak)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOldal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldal1ActionPerformed
        aktualisOldal1(1);
        aktualisOldal1(270);
        aktualisOldal1(66);
    }//GEN-LAST:event_btnOldal1ActionPerformed

    private void aktualisOldal1(int oldal) {
        if(oldal == 1){
            lblOldalSzam.setText("270");
        }
        if(oldal == 270){
            btnOldal1.setEnabled(false);
        }
        if(oldal == 66){
            btnOldal1.setText("56");
        }
    }



    private void btnOldal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldal2ActionPerformed
        aktualisOldal2(1);
        aktualisOldal2(66);
    }//GEN-LAST:event_btnOldal2ActionPerformed
    
    private void aktualisOldal2(int oldal) {
        if(oldal == 1){
            lblOldalSzam.setText("66");
        }
        if(oldal == 66){
            btnOldal1.setText("293");
            btnOldal1.setEnabled(true);
        }
        
    }
    private void btnToStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToStartActionPerformed
        felhasznaloNev = txfFelhasznaloNev.getText();
        String hibaSzoveg1 = "A felhasználónév nem éri el a minimum 3 karaktert!";
        String hibaSzoveg2 = "A felhasználónév túllépte a maximum 15 karaktert!";
        if(felhasznaloNev.length() > 2 && felhasznaloNev.length() < 16){
            tpOldalak.setSelectedIndex(1);
            lblFelhNev.setText(felhasznaloNev);
        }
        else if (felhasznaloNev.length() < 2){
            JOptionPane.showMessageDialog(rootPane, hibaSzoveg1, "Hiba", 2);
        }
        else if (felhasznaloNev.length() > 16){
            JOptionPane.showMessageDialog(rootPane, hibaSzoveg2, "Hiba", 2);
        }
        
        
    }//GEN-LAST:event_btnToStartActionPerformed

    private void btnToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToInventoryActionPerformed
        tpOldalak.setSelectedIndex(2);
    }//GEN-LAST:event_btnToInventoryActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabirintusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabirintusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabirintusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabirintusGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabirintusGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOldal1;
    private javax.swing.JButton btnOldal2;
    private javax.swing.JButton btnToInventory;
    private javax.swing.JButton btnToStart;
    private javax.swing.JLabel lblAtk;
    private javax.swing.JLabel lblAtk1;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblDef1;
    private javax.swing.JLabel lblFelhNev;
    private javax.swing.JLabel lblHp;
    private javax.swing.JLabel lblHp1;
    private javax.swing.JLabel lblKepAtk;
    private javax.swing.JLabel lblKepAtk1;
    private javax.swing.JLabel lblKepCoin;
    private javax.swing.JLabel lblKepCoin1;
    private javax.swing.JLabel lblKepDef;
    private javax.swing.JLabel lblKepDef1;
    private javax.swing.JLabel lblKepSziv;
    private javax.swing.JLabel lblKepSziv1;
    private javax.swing.JLabel lblOldalSzam;
    private javax.swing.JLabel lblPenz;
    private javax.swing.JLabel lblPenz1;
    private javax.swing.JLabel lblSzovegFelhasznalonev;
    private javax.swing.JLabel lblTxtOldalSz;
    private javax.swing.JPanel pnlGame;
    private javax.swing.JPanel pnlGameHud;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlOldalSzam;
    private javax.swing.JPanel pnlPlayerInfo;
    private javax.swing.JPanel pnlPlayerInfo1;
    private javax.swing.JScrollPane scpJatekInfo;
    private javax.swing.JScrollPane scpOldalInfo;
    private javax.swing.JTabbedPane tpOldalak;
    private javax.swing.JTextArea txaOldalnfo;
    private javax.swing.JTextArea txaOldalnfo1;
    private javax.swing.JTextField txfFelhasznaloNev;
    // End of variables declaration//GEN-END:variables
}
